### ISSUE TITLE
meson.build:1:0: ERROR on Linux Mint 19.1

### ISSUE THREAD

**Issue by DJMyles** [FeralInteractive/gamemode#137]
When I attempt to run ./bootstrap.sh I get:

```
dj@Minty:~/gamemode$ ./bootstrap.sh
+ meson --prefix=/usr build --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.45.1
Source dir: /home/dj/gamemode
Build dir: /home/dj/gamemode/build
Build type: native build
Project name: gamemode

meson.build:1:0: ERROR: Compiler cc can not compile programs.

A full log can be found at /home/dj/gamemode/build/meson-logs/meson-log.txt

```
Full meson-log.txt:

```
Build started at 2019-05-08T16:24:12.301994
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/dj/gamemode
Build dir: /home/dj/gamemode/build
Build type: native build
Project name: gamemode
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/dj/gamemode/build/meson-private/sanitycheckc.c -o /home/dj/gamemode/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status

-----

meson.build:1:0: ERROR: Compiler cc can not compile programs.
```
I have all the necessary dependencies installed as per the readme

```
dj@Minty:~$ apt install meson libsystemd-dev pkg-config ninja-build git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu2).
meson is already the newest version (0.45.1-2).
ninja-build is already the newest version (1.8.2-1).
git is already the newest version (1:2.17.1-1ubuntu0.4).
libsystemd-dev is already the newest version (237-3ubuntu10.21).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

```
Anyone got any ideas why it's failing?

**Comment by aejsmith** [comment]
That suggests you're still missing some dependencies. Try: `apt install build-essential`

**Comment by DJMyles** [comment]
Timely reply, I just fixed it.

For anyone curious the fix was:

`sudo apt install gcc-multilib`

**Comment by hadbabits** [comment]
Glad I found this, why hasn't gcc-multilib been added to the dependencies?

**Comment by vcolano** [comment]
@DJMyles' answer got me past that error but now I get
```
The Meson build system
Version: 0.45.1
Source dir: /home/vito/Downloads/gamemode
Build dir: /home/vito/Downloads/gamemode/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -Waggregate-return: YES
Compiler for C supports argument -Wunused: YES
Compiler for C supports argument -Warray-bounds: YES
Compiler for C supports argument -Wcast-align: YES
Compiler for C supports argument -Wclobbered: YES
Compiler for C supports argument -Wempty-body: YES
Compiler for C supports argument -Wformat=2: YES
Compiler for C supports argument -Wformat-nonliteral: YES
Compiler for C supports argument -Wformat-signedness: YES
Compiler for C supports argument -Wignored-qualifiers: YES
Compiler for C supports argument -Wimplicit-function-declaration: YES
Compiler for C supports argument -Winit-self: YES
Compiler for C supports argument -Wmissing-format-attribute: YES
Compiler for C supports argument -Wmissing-include-dirs: YES
Compiler for C supports argument -Wmissing-noreturn: YES
Compiler for C supports argument -Wmissing-parameter-type: YES
Compiler for C supports argument -Wnested-externs: YES
Compiler for C supports argument -Wno-discarded-qualifiers: YES
Compiler for C supports argument -Wno-missing-field-initializers: YES
Compiler for C supports argument -Wno-suggest-attribute=format: YES
Compiler for C supports argument -Wno-unused-parameter: YES
Compiler for C supports argument -Wold-style-definition: YES
Compiler for C supports argument -Woverride-init: YES
Compiler for C supports argument -Wpointer-arith: YES
Compiler for C supports argument -Wredundant-decls: YES
Compiler for C supports argument -Wreturn-type: YES
Compiler for C supports argument -Wshadow: YES
Compiler for C supports argument -Wsign-compare: YES
Compiler for C supports argument -Wstrict-aliasing=3: YES
Compiler for C supports argument -Wstrict-prototypes: YES
Compiler for C supports argument -Wstringop-overflow: YES
Compiler for C supports argument -Wstringop-truncation: NO
Compiler for C supports argument -Wtype-limits: YES
Compiler for C supports argument -Wundef: YES
Compiler for C supports argument -Wuninitialized: YES
Compiler for C supports argument -Wunused-but-set-variable: YES
Compiler for C supports argument -Wwrite-strings: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 237
Native dependency dbus-1 found: YES 1.12.2
Dependency threads found: YES
Library dl found: YES
Checking for function "pidfd_open": NO
Configuring build-config.h using configuration

Executing subproject inih.

Also couldn't find a fallback subproject in subprojects/inih for the dependency inih 
Reason: Meson version is 0.45.1 but project requires >= 0.46.0.

Dependency inih not found but it is available in a sub-subproject.
To use it in the current project, promote it by going in the project source
root and issuing the following command.

meson wrap promote subprojects/inih

meson.build:160:4: ERROR: Native dependency 'inih' not found

A full log can be found at /home/vito/Downloads/gamemode/build/meson-logs/meson-log.txt
```

I've tried installing all of these but still get the same error:
```
vito@t480s:~/Downloads/gamemode$ apt search inih
p   libconfig-inihash-perl         - Perl extension for reading and writing IN
i   libinih-dev                    - simple .INI file parser (development file
p   libinih-dev:i386               - simple .INI file parser (development file
i   libinih1                       - simple .INI file parser                  
p   libinih1:i386                  - simple .INI file parser                  
```

On Mint 19.1

Thanks!
