### ISSUE TITLE
/usr/bin/gamemoded: error while loading shared libraries: libinih.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jhilliker** [FeralInteractive/gamemode#280]
**Describe the bug**
gamemode fails to run due to missing inih library

Not sure if this is the right place to report this or if it's a problem with the AUR package.  Previous AUR version (built from https://github.com/FeralInteractive/gamemode/releases/download/1.5.1/gamemode-1.5.1.tar.xz) worked fine without inih present.  Possibly related to faea358 and f95470c ?

Build works fine. During build, get:
```
Run-time dependency inih found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency inih

|Executing subproject inih method meson
|
|Project name: inih
|Project version: 49
|Using 'CXXFLAGS' from environment with value: '-march=x86-64 -mtune=generic -O2 -pipe -fno-plt'
|Using 'LDFLAGS' from environment with value: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
|Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=2'
|C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
|C linker for the host machine: cc ld.bfd 2.35
|Using 'CXXFLAGS' from environment with value: '-march=x86-64 -mtune=generic -O2 -pipe -fno-plt'
|Using 'LDFLAGS' from environment with value: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
|Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=2'
|C++ compiler for the host machine: c++ (gcc 10.2.0 "c++ (GCC) 10.2.0")
|C++ linker for the host machine: c++ ld.bfd 2.35
|Build targets in project: 8
|Subproject inih finished.

Dependency inih from subproject subprojects/inih found: YES 49
...
gamemode 1.6-dev

  Subprojects
    inih: YES
```

On execute, getting:
```
Sep 11 16:13:11 *** systemd[969]: Starting gamemoded...
Sep 11 16:13:11 *** systemd[969]: gamemoded.service: Main process exited, code=exited, status=127/n/a
Sep 11 16:13:11 *** systemd[969]: gamemoded.service: Failed with result 'exit-code'.
Sep 11 16:13:11 *** gamemoded[2329]: /usr/bin/gamemoded: error while loading shared libraries: libinih.so.0: cannot open shared object file: No such file or directory
Sep 11 16:13:11 *** systemd[969]: Failed to start gamemoded.
```

**To Reproduce**
``gamemoderun top``

**Expected behavior**
Expected ``gamemoded`` to start.  It doesnt.

**System Info (please complete the following information):**
  - Arch Linux
  -  ``5.8.8-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 09 Sep 2020 19:01:48 +0000 x86_64 GNU/Linux``
 -  ``gamemode 1.6-dev``

**Additional context**
Using https://aur.archlinux.org/packages/gamemode/

has  (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gamemode):
```
pkgname=('gamemode')
pkgver=1.6
pkgrel=1
pkgdesc="A daemon/lib combo for Linux that allows games to request a set of optimisations be temporarily applied to the host OS"
arch=('x86_64')
url="https://github.com/FeralInteractive/gamemode.git"
license=('BSD 3-Clause License (Revised)')
optdepends=('systemd')
depends=('polkit')
makedepends=('meson' 'ninja' 'pkg-config')
source=("https://github.com/FeralInteractive/gamemode/releases/download/$pkgver/$pkgname-$pkgver.tar.xz"
)
sha256sums=('4fec5a0900e8f559b37cf1711ca7dcea7e1cebfe1237ce314001f65c1e346a5d'
)

build() {
  meson gamemode-$pkgver build --prefix /usr --libexecdir lib/gamemode -Dwith-pam-group=gamemode -Dwith-systemd-user-unit-dir=/usr/lib/systemd/user
  #meson ${_pkgname} build --prefix /usr -Dwith-systemd-user-unit-dir=/usr/lib/systemd/user -Dwith-pam-group=gamemode
  ninja -C build
}

package() {
  DESTDIR=$pkgdir ninja -C build install
  install -m644 -Dt "${pkgdir}/usr/share/licenses/${pkgname}" ${pkgname}-${pkgver}/LICENSE.txt
  install -m644 -Dt "${pkgdir}/usr/share/doc/${pkgname}/example" ${pkgname}-${pkgver}/example/gamemode.ini
}
```

**Comment by Zenzi0** [comment]
Reinstalling and telling my AUR-helper (yay) to clean-build the package fixed it for me. At least I think you have the same problem as I have had.

**Comment by bg2908** [comment]
@Zenzi0 's solution work for me too.

**Comment by mrazster** [comment]
Had the same issue running Arch, after the 1.6 Gamemode update.
But.. removing, rebuilding (clean-build) and reinstalling fixed it.

Thanx a bunch !

**Comment by mrazster** [comment]
> Reinstalling and telling my AUR-helper (yay) to clean-build the package fixed it for me. At least I think you have the same problem as I have had.

Thanx a bunch !

Had the same issue running Arch, after the 1.6 Gamemode update.
But.. removing, rebuilding (clean-build) and reinstalling fixed it.

**Comment by abienz** [comment]
This doesn't appear to work for me, I have cleared my cached package files and redownloaded them, when I check the service I get the following:

```
✘  ~  systemctl --user status gamemoded.service
● gamemoded.service - gamemoded
     Loaded: error (Reason: Unit gamemoded.service failed to load properly: Device or resource busy.)
     Active: failed (Result: exit-code) since Fri 2020-09-18 19:15:13 BST; 12min ago
   Main PID: 12978 (code=exited, status=127)

Sep 18 19:15:13 arch-desk systemd[791]: Starting gamemoded...
Sep 18 19:15:13 arch-desk gamemoded[12978]: /usr/bin/gamemoded: error while loading shared libraries: libinih.so.0: cannot open shared object file: No such file or directory
Sep 18 19:15:13 arch-desk systemd[791]: gamemoded.service: Main process exited, code=exited, status=127/n/a
Sep 18 19:15:13 arch-desk systemd[791]: gamemoded.service: Failed with result 'exit-code'.
Sep 18 19:15:13 arch-desk systemd[791]: Failed to start gamemoded.
```

**Comment by jhilliker** [comment]
Issue seems resolved in the Arch package.
Arch package has added `libinih` as a dependency.

**Comment by tteskac** [comment]
For anyone else still not being able to install it here's another solution I found on the link below:
```
cd builddir/subprojects/inih
sudo cp libinih.so* /usr/lib -P
gamemoded --version
```

Source: https://www.bountysource.com/issues/94948572-libinih-so-0-cannot-open-shared-object-file-under-ubuntu-18-04
