### ISSUE TITLE
Easier installation in Ubuntu

### ISSUE THREAD

**Issue by vadi2** [FeralInteractive/gamemode#58]
**Is your feature request related to a problem? Please describe.**

I would love to see a way to get this going easier in Ubuntu.

**Describe the solution you'd like**

PPA repository, .deb package, snap, flatpak, AppImage, anything would do.

**Describe alternatives you've considered**

Compiling... not fun.

**Additional context**

**Comment by fuckyourselfup** [comment]
This mainly depends on community members responsible for packaging rather than Feral. There was a try from a Debian team member to build a DEB, but it seemed to be stalled weeks ago.

https://salsa.debian.org/games-team/gamemode

**Comment by skarmiglione** [comment]
how can i uninstall it?

**Comment by vadi2** [comment]
I don't think this is the right topic for it - open a [new issue](https://github.com/FeralInteractive/gamemode/issues/new/choose) please.

**Comment by Sunderland93** [comment]
I create PPA, based on Debian's work: https://launchpad.net/~samoilov-lex/+archive/ubuntu/gamemode

**Comment by fuckyourselfup** [comment]
> I create PPA, based on Debian's work: https://launchpad.net/~samoilov-lex/+archive/ubuntu/gamemode

Sunderland93, are you going to continue supporting gamemode's Ubuntu release? Latest release from your PPA is 1.2 from August 2018.

**Comment by Sunderland93** [comment]
@fuckyourselfup updated, sorry for delay

**Comment by vadi2** [comment]
thank you!

**Comment by takatakatakatak** [comment]
Thanks, @Sunderland93.

Is there a way to use your PPA to force the installation of 32-bit gamemode?

It seems I need both 32 and 64 bit installs to get feral gamemode working in Lutris.

**Comment by rsd** [comment]
> Thanks, @Sunderland93.
> 
> Is there a way to use your PPA to force the installation of 32-bit gamemode?
> 
> It seems I need both 32 and 64 bit installs to get feral gamemode working in Lutris.

Same issue here

**Comment by Batcastle** [comment]
@Sunderland93 I have been building a *.deb that builds gamemode from source. It's a real chore XD. How long are you planning to keep building your package? If at all possible I would like to replace my package with yours in my repository (this is for an OS i am developing). But if you aren't going to keep building it for much longer then if you don't mind sharing your build process I would appreciate it.

Thanks!

**Comment by regulator-g** [comment]
Can gamemode devs please take on the task of providing and updating a repo?

@Sunderland93 thanks for your help so far

**Comment by Sunderland93** [comment]
Sorry for delay. I'll fix all bugs soon and add 32 bit package

**Comment by Sunderland93** [comment]
Sorry for delay. I'll fix all issues soon

**Comment by Sunderland93** [comment]
>     Is there a way to use your PPA to force the installation of 32-bit gamemode?
> 
>     It seems I need both 32 and 64 bit installs to get feral gamemode working in Lutris.
> 
> Same issue here

Fixed

**Comment by birdstream** [comment]
@Sunderland93 I added your PPA and tried to apt install gamemode gamemode:i386, but it won't let me because of some package conflict between the two. One at a time seem to work but :i386 removes the x64 version and vice versa. Am i doing something wrong here?

**Comment by rsd** [comment]
Almost there

```
raul@nostromo:~$ sudo apt install libgamemode0:i386 libgamemodeauto0:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  gamemode libgamemode0 libgamemodeauto0
The following NEW packages will be installed:
  libgamemode0:i386 libgamemodeauto0:i386
0 upgraded, 2 newly installed, 3 to remove and 0 not upgraded.
Need to get 0 B/14,7 kB of archives.
After this operation, 183 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

**Comment by Sunderland93** [comment]
Hm, there is no conflicts on build scripts.....I'll try to figure out

**Comment by Sunderland93** [comment]
There is problem to build two different packages (with different build options) from one tarball. Arch Linux solve this with `lib32-gamemode` package. I'll try to make similar

**Comment by Sunderland93** [comment]
@birdstream please install `gamemode-lib32` package

**Comment by birdstream** [comment]
@Sunderland93 Thanks! I will try this as soon as I get back home tonight :)

**Comment by birdstream** [comment]
@Sunderland93 Unfortunately installing gamemode-lib32 gives exactly the same issue: It deletes gamemode:amd64
To be more precise, gamemode-lib32 depends on libgamemode0:i386 and libgamemodeauto0:i386 but  they seem to not be able to coensist with libgamemode0:amd64 and libgamemodeauto0:amd64. At least on my system (Ubuntu 18.04)

**Comment by Sunderland93** [comment]
@birdstream should be fixed now

**Comment by arnishow** [comment]
@Sunderland93 could you please make it works for disco as well?

**Comment by magicmyth** [comment]
I'm still getting the same issue as birdstream of gamemode-lib32 failing to install on Kubuntu 18.04 due to '/usr/bin/gamemoded' being present in both gamemode and gamemode-lib32 packages.

Console output log:
```
$ sudo apt install gamemode-lib32
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  gamemode-lib32:i386
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/47.6 kB of archives.
After this operation, 163 kB of additional disk space will be used.
(Reading database ... 306514 files and directories currently installed.)
Preparing to unpack .../gamemode-lib32_1.4.0-9~bionic_i386.deb ...
Unpacking gamemode-lib32:i386 (1.4.0-9~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/gamemode-lib32_1.4.0-9~bionic_i386.deb (--unpack):
 trying to overwrite '/usr/bin/gamemoded', which is also in package gamemode 1.4.0-6~bionic
Errors were encountered while processing:
 /var/cache/apt/archives/gamemode-lib32_1.4.0-9~bionic_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mdiluz** [comment]
The issue then seems to be that the lib32 package contains the daemon, it shouldn't. Perhaps there needs to be `gamemode:amd64`, `libgamemode:amd64` and `libgamemode:i386` packages

**Comment by rsd** [comment]
Any chance to get it to 19.04 too?

**Comment by Sunderland93** [comment]
@mdiluz fixed

**Comment by Sunderland93** [comment]
@rsd Yes

**Comment by takatakatakatak** [comment]
Right, so who can give me the proper commands to fully install 32 and 64 bit?

**Comment by magicmyth** [comment]
This is still failing for Bionic. I can see in the PPA there has been an update  to 1.4.0-10\~bionic but something seems to be wrong as http://ppa.launchpad.net/samoilov-lex/gamemode/ubuntu/pool/main/g/gamemode-lib32/ shows there is only a gamemode-lib32_1.4.0-9~bionic_i386.deb in the repo, not a newer one. Are we supposed to instead install `lib32gamemode0`?

**Comment by Sunderland93** [comment]
Try `sudo apt install gamemode lib32gamemode0`

**Comment by magicmyth** [comment]
Thanks but its still failing. To give it a better chance I uninstalled gamemode then attempted again with the following results:
```
$ sudo apt install gamemode lib32gamemode0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgamemode0 libgamemodeauto0
The following NEW packages will be installed
  gamemode lib32gamemode0 libgamemode0 libgamemodeauto0
0 to upgrade, 4 to newly install, 0 to remove and 0 not to upgrade.
Need to get 65.7 kB/74.5 kB of archives.
After this operation, 273 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/samoilov-lex/gamemode/ubuntu bionic/main amd64 libgamemode0 amd64 1.4.0-6~bionic [8,828 B]
Get:2 http://ppa.launchpad.net/samoilov-lex/gamemode/ubuntu bionic/main amd64 libgamemodeauto0 amd64 1.4.0-6~bionic [5,884 B]
Get:3 http://ppa.launchpad.net/samoilov-lex/gamemode/ubuntu bionic/main amd64 gamemode amd64 1.4.0-6~bionic [50.9 kB]
Fetched 65.7 kB in 0s (385 kB/s)   
Selecting previously unselected package libgamemode0.
(Reading database ... 306350 files and directories currently installed.)
Preparing to unpack .../libgamemode0_1.4.0-6~bionic_amd64.deb ...
Unpacking libgamemode0 (1.4.0-6~bionic) ...
Selecting previously unselected package libgamemodeauto0.
Preparing to unpack .../libgamemodeauto0_1.4.0-6~bionic_amd64.deb ...
Unpacking libgamemodeauto0 (1.4.0-6~bionic) ...
Selecting previously unselected package gamemode.
Preparing to unpack .../gamemode_1.4.0-6~bionic_amd64.deb ...
Unpacking gamemode (1.4.0-6~bionic) ...
Preparing to unpack .../lib32gamemode0_1.4.0-7~bionic_amd64.deb ...
Unpacking lib32gamemode0 (1.4.0-7~bionic) ...
dpkg: error processing archive /var/cache/apt/archives/lib32gamemode0_1.4.0-7~bionic_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/cpugovctl', which is also in package libgamemode0 1.4.0-6~bionic
Errors were encountered while processing:
 /var/cache/apt/archives/lib32gamemode0_1.4.0-7~bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
So it seems there is a different clash now. Looking at that either `/usr/lib/x86_64-linux-gnu/cpugovctl` needs removing from lib32gamemode0 or it shoule install to `/usr/lib/i386-linux-gnu/cpugovctl`?

**Comment by mdiluz** [comment]
I'd like to see some clarification in this bug about what the on-going issue is. The current status, as far as I know, is that Ubuntu/Debian has a valid [package](https://packages.ubuntu.com/disco/gamemode), a simple `apt install gamemode`, but the issue is that it doesn't contain the 32bit version of `libgamemode` which Lutris looks for.

If the issue is just the above, or more complicated, then let's separate things out into separate reports. It seems like this one has gone on a tangent from the original report from @vadi2 that appears to now be resolved.

**Comment by vadi2** [comment]
Yep true, I'll close this.

**Comment by thunder1410** [comment]
@magicmyth have you figured out how to install the 32 bit version for lutris? I am getting the same error using the PPA on ubuntu 18.04.

**Comment by BassmanBiff** [comment]
Same on Mint 19.2. A link to whatever new issue was made would be appreciated! Or to wherever this is being discussed.

**Comment by BassmanBiff** [comment]
Update: I built and installed libstrangle, which magically enabled gamemode. So, either libstrangle or its dependency libc6-dev-i386 is required to enable gamemode right now. (Mint 19.2)

**Comment by BloodyIron** [comment]
Considering gamemode is in the main PPAs for Ubuntu, can we please get the 32bit versions included into that too? I can't get Lutris to recognise gamemode is available and it seems it's because I don't have 32bit gamemode installed. Compiling from source really is only an acceptable thing to do in Alpha and Beta phase of testing, but in general use/production, it should not be acceptable. Primarily because your package manager is unaware of it.

Please? :)

**Comment by tannisroot** [comment]
@BloodyIron it's already included in the PPA 
![image](https://user-images.githubusercontent.com/10602045/70420160-1e999200-1a78-11ea-85d7-68d4d434a8ca.png)

**Comment by BloodyIron** [comment]
> @BloodyIron it's already included in the PPA
> ![image](https://user-images.githubusercontent.com/10602045/70420160-1e999200-1a78-11ea-85d7-68d4d434a8ca.png)

I said the main PPA, as in the main repositories that ship with Ubuntu, not 3rd party repos.

**Comment by tannisroot** [comment]
For Gamemode to appear in official Ubuntu repositories, it has to be packaged in official Debian repositories first, and AFAIK it isn't. For now you have to use the 3rd party PPAs.

**Comment by BloodyIron** [comment]
It is in the main repos though : https://packages.ubuntu.com/search?keywords=gamemode

**Comment by richard378** [comment]
The main Ubuntu 19.10 repo only includes 64-bit gamemode, so we need to compile from source or use a PPA for 32-bit gamemode.

**Comment by highvoltage** [comment]
> The main Ubuntu 19.10 repo only includes 64-bit gamemode, so we need to compile from source or use a PPA for 32-bit gamemode.

I'll take a look at getting the 32bit support for the debian package too, perhaps it could still make it in for ubuntu 20.04.

**Comment by lucifertdark** [comment]
Compiling is simple these days, just follow the simple instructions & it's installed & working in less than a minute.

**Comment by BloodyIron** [comment]
> Compiling is simple these days, just follow the simple instructions & it's installed & working in less than a minute.

Package managers need to be aware of what's installed so you can update or remove it centrally.
